import { createContext, useMemo, useState } from 'react';

export const LanguageContext = createContext(null);

const dictionary = {
  en: {
    // ─── App ───────────────────────────────────────────────────────────────
    appName: 'HealthBot',

    // ─── Navbar ────────────────────────────────────────────────────────────
    dashboard: 'Dashboard',
    chat: 'Chat',
    symptomChecker: 'Symptom Checker',
    symptoms: 'Symptoms',
    history: 'Health History',
    reports: 'Reports',
    profile: 'Profile',
    healthTips: 'Health Tips',
    hospitals: 'Hospitals',
    admin: 'Admin',
    login: 'Login',
    logout: 'Logout',
    signIn: 'Sign in',
    signOut: 'Sign out',
    settings: 'Settings',
    adminPanel: 'Admin Panel',
    languageToggle: 'EN / HI',

    // ─── Landing page ──────────────────────────────────────────────────────
    landingTagline: 'AI health awareness platform',
    landingTitle: 'Understand symptoms and choose the next step with confidence.',
    landingSubtitle: 'HealthBot brings AI chat, guided symptom checks, reports, and hospital discovery into one calm, secure workspace for everyday health decisions.',
    getStarted: 'Get started',
    signInToChat: 'Sign in to chat',
    aiGuidance247: '24/7',
    aiGuidanceLabel: 'AI guidance',
    riskStatLabel: 'Risk',
    riskAwareLabel: 'aware triage',
    secureLabel: 'Secure',
    historyLabel: 'history',
    platformFeaturesEyebrow: 'Platform features',
    platformFeaturesTitle: 'Everything users need after the first symptom',
    platformFeaturesDesc: 'Elevated cards, clinical clarity, and the same dark-mode polish as the authenticated workspace.',
    howItWorksEyebrow: 'How it works',
    howItWorksTitle: 'A guided flow from symptoms to action',
    howItWorksDesc: 'Simple steps keep the experience focused while preserving the context needed for reports, history, and care discovery.',
    readyWhenYouAre: 'Ready when you are',
    startHealthTrail: 'Start a cleaner health assessment trail today.',
    createAccountDesc: 'Create an account to keep chats, symptom checks, reports, and hospital recommendations connected in one secure workspace.',
    createAccount: 'Create account',
    liveAssessment: 'Live assessment',
    careGuidance: 'Care guidance',
    symptomContextLabel: 'Symptom context',
    riskReviewLabel: 'Risk review',
    recommendedActionLabel: 'Recommended action',
    exploreWorkflow: 'Explore workflow',
    stepLabel: 'Step',
    triage: 'Triage',

    // Landing feature cards
    feature_aiChat_title: 'AI Health Chat',
    feature_aiChat_desc: 'Structured health guidance with next steps, safety checks, and clear care recommendations.',
    feature_symptomChecker_title: 'Symptom Checker',
    feature_symptomChecker_desc: 'Guided triage that captures duration, severity, related symptoms, and risk level.',
    feature_hospitalDiscovery_title: 'Hospital Discovery',
    feature_hospitalDiscovery_desc: 'Find nearby care options by specialty when symptoms need clinical attention.',
    feature_healthReports_title: 'Health Reports',
    feature_healthReports_desc: 'Visual summaries that turn conversations and symptom checks into useful trends.',
    feature_medicalHistory_title: 'Medical History',
    feature_medicalHistory_desc: 'Keep an organized timeline of past health activity without digging through chats.',
    feature_healthInsights_title: 'Health Insights',
    feature_healthInsights_desc: 'Daily tips and alerts that help users stay informed between care decisions.',

    // Landing how-it-works steps
    step1_title: 'Share symptoms',
    step1_desc: 'Start with a chat or guided checker and add the details that matter.',
    step2_title: 'Review risk',
    step2_desc: 'HealthBot summarizes severity, possible next steps, and urgency signals.',
    step3_title: 'Act with context',
    step3_desc: 'Save the assessment, monitor reports, or discover hospitals when needed.',

    // ─── Dashboard ─────────────────────────────────────────────────────────
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    welcomeBack: 'Welcome back. Check your health today — a quick chat takes 30 seconds.',
    recentHighRisk: 'You had a high-risk event',
    howAreYouFeeling: 'How are you feeling now?',
    openChat: 'Open Chat',
    healthScore: 'Health Score',
    activeStreak: 'Active Streak',
    daysEngaged: 'days engaged',
    healthRecords: 'Health Records',
    totalEntries: 'total entries',
    notifications: 'Notifications',
    newUpdates: 'new updates',
    quickActions: 'Quick Actions',
    recentActivity: 'Recent Activity',
    todaysTips: "Today's Tips",
    viewAll: 'View all',
    allTips: 'All tips',
    noActivityYet: 'No activity yet — start with a chat or symptom check.',
    noTipsAvailable: 'No tips available right now.',
    aiChat: 'AI Chat',
    wellness: 'Wellness',

    // ─── Chat page ─────────────────────────────────────────────────────────
    chatbotTitle: 'Health Chatbot',
    chatbotSubtext: 'Start a fresh health check whenever you want a clean assessment trail.',
    newAssessment: 'Start New Health Assessment',
    askPlaceholder: 'Ask a health question… (Enter to send, Shift+Enter for new line)',
    askAi: 'Ask AI',
    generating: 'Generating...',
    startConversation: 'Start a conversation',
    startConversationDesc: "Ask a health question and I'll provide information based on verified medical sources.",
    healthChatbotHeader: 'Health Chatbot',
    aiHealthAwareness: 'AI-powered health awareness — not a substitute for medical advice',
    chatDisclaimer: 'HealthBot may make mistakes. Verify important health information with a qualified professional.',
    dismiss: 'Dismiss',
    couldNotLoadConversation: 'Could not load conversation',
    couldNotStartConversation: 'Could not start conversation',

    // Chat structured response
    summary: 'Health Assessment Summary',
    symptomsDetected: 'Symptoms detected',
    riskLevel: 'Risk Level',
    recommendedAction: 'Recommended Action',
    highAction: 'Seek urgent medical help and use the recommended hospitals below.',
    mediumAction: 'Monitor symptoms closely and book a doctor consultation if they continue.',
    lowAction: 'Rest, hydration, and observation are recommended for now.',
    nextSteps: 'Next Steps',
    nextStepsBody: 'Monitor symptoms for 2 to 3 days, or act sooner if warning signs appear.',
    chatHistory: 'Chat History',
    noChats: 'No chats yet.',
    possibleCauses: 'Possible Causes',
    prevention: 'Prevention',
    consultDoctor: 'When to Consult Doctor',
    recommendedHospitals: 'Recommended Hospitals',
    liveUpdate: 'Latest assessment synced in real time.',
    confidence: 'Confidence',
    promptVersion: 'Prompt Version',

    // ─── Symptom Checker ───────────────────────────────────────────────────
    guidedTriage: 'Guided Triage',
    stepPrimarySymptoms: 'Primary Symptoms',
    stepDurationSeverity: 'Duration & Severity',
    stepAssociatedSymptoms: 'Associated Symptoms',
    stepHealthProfile: 'Health Profile',
    stepResult: 'Result',
    selectPrimarySymptoms: 'Select your primary symptoms',
    searchSymptoms: 'Search symptoms',
    duration: 'Duration',
    severity: 'Severity',
    mildLabel: '1 = Mild',
    moderateLabel: '5 = Moderate',
    severeLabel: '10 = Severe',
    associatedSymptoms: 'Associated symptoms',
    noneOfThese: 'None of these',
    healthProfileSnapshot: 'Health profile snapshot',
    age: 'Age',
    gender: 'Gender',
    genderNotSpecified: 'Not specified',
    genderMale: 'Male',
    genderFemale: 'Female',
    genderOther: 'Other',
    genderPreferNot: 'Prefer not to say',
    city: 'City',
    cityPlaceholderShort: 'e.g. Phagwara',
    medicalNotes: 'Medical notes',
    analysingSymptoms: 'Analysing your symptoms...',
    emergencyWarningTitle: 'Emergency warning signs detected',
    emergencyWarningDesc: 'Please seek urgent medical care immediately.',
    assessmentResult: 'Assessment Result',
    recommendedActions: 'Recommended actions',
    suggestedSpecialists: 'Suggested specialists',
    nearestHospitals: 'Nearest hospitals',
    noNearbyHospitals: 'No nearby hospital suggestions found for your city.',
    back: 'Back',
    next: 'Next',
    getAssessment: 'Get Assessment',
    startOver: 'Start Over',
    saveToHistory: 'Save to History',
    continueInChat: 'Continue in Chat',
    other: 'Other',
    describeOtherSymptom: 'Describe other symptom',
    noSymptomsMatch: 'No symptoms match your search.',
    savedToHistory: 'Saved to your health history.',
    analysisFailedRetry: 'Analysis failed. Please try again.',
    couldNotOpenChat: 'Could not open chat. Please navigate to Chat manually.',

    // ─── Hospitals page ────────────────────────────────────────────────────
    findHospitals: 'Find Hospitals',
    searchByCityOrLocation: 'Search by city or use your location for nearby care.',
    useMyLocation: 'Use My Location',
    shareLocation: 'Share Location',
    shareLocationDesc: 'Share your location to sort hospitals by distance and enable radius filtering.',
    allSpecialties: 'All specialties',
    emergencyOnly: 'Emergency only',
    anyDistance: 'Any distance',
    kmAway: 'km away',
    minDrive: 'min drive',
    emergency24h: '24h emergency',
    searchHospitalsTitle: 'Search for hospitals',
    enterCityOrLocation: 'Enter a city or share your location to begin.',
    noHospitalsFound: 'No hospitals found',
    tryDifferentSearch: 'Try a different city, specialty, or distance.',
    noHospitalsWithinRadius: 'No hospitals found within',
    tryIncreasingRadius: 'Try increasing the search radius or selecting a different specialty.',
    quickSearch: 'Quick city search',
    showingForSymptoms: 'Showing hospitals based on your recent symptom check.',
    call: 'Call',
    directions: 'Directions',
    hospitalsFoundSingular: 'hospital found',
    hospitalsFoundPlural: 'hospitals found',
    locationDetected: 'Location detected',
    clearLocation: 'Clear location',
    locationDenied: 'Location access was denied. Please allow location access in your browser settings, then retry.',
    locationTimeout: 'Location request timed out. Please try again.',
    locationUnavailable: 'Could not detect your location. Please search by city instead.',
    geoNotSupported: 'Geolocation is not supported in this browser',
    retryLocation: 'Retry',
    cityPlaceholder: 'City, e.g. Phagwara, Ludhiana, Delhi',
    detectingLocation: 'Detecting location...',
    locationPermissionDenied: 'Location permission denied',
    locationTimedOut: 'Location request timed out',
    couldNotDetectLocation: 'Could not detect location',
    couldNotLoadHospitals: 'Could not load hospitals',

    // ─── Health Reports ────────────────────────────────────────────────────
    healthReportsTitle: 'Health Reports',
    overviewTab: 'Overview',
    symptomsTab: 'Symptoms',
    trendsTab: 'Trends',
    aiInsightsTab: 'AI Insights',
    downloadPdf: 'Download PDF',
    refreshData: 'Refresh',
    totalChecks: 'Total Checks',
    highRiskEvents: 'High Risk Events',
    avgRiskScore: 'Avg Risk Score',
    reportPeriod: 'Report Period',
    noReportData: 'No report data yet.',
    startCheckForReport: 'Complete a symptom check or chat to generate your first report.',
    couldNotLoadInsights: 'Could not load AI insights.',
    regenerateInsights: 'Regenerate Insights',
    aiInsightsTitle: 'AI Health Insights',
    noInsightsYet: 'No insights yet.',
    completeChecksForInsights: 'Complete a few symptom checks to generate personalized insights.',

    // ─── Health History ────────────────────────────────────────────────────
    healthHistoryTitle: 'Health History',
    healthHistoryDesc: 'Your past symptom checks and AI conversations.',
    noHistoryYet: 'No health history yet.',
    startChatOrCheck: 'Start a chat or symptom check to build your health record.',

    // ─── Health Tips ───────────────────────────────────────────────────────
    healthTipsTitle: 'Health Tips',
    healthTipsDesc: 'Daily wellness advice and preventive care guidance.',

    // ─── Profile ───────────────────────────────────────────────────────────
    profileTitle: 'Profile & Settings',
    editProfile: 'Edit Profile',
    saveChanges: 'Save Changes',

    // ─── Common / shared ───────────────────────────────────────────────────
    loading: 'Loading...',
    error: 'Error',
    retry: 'Retry',
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    youAreHere: 'You are here',
  },

  hi: {
    // ─── App ───────────────────────────────────────────────────────────────
    appName: 'हेल्थबॉट',

    // ─── Navbar ────────────────────────────────────────────────────────────
    dashboard: 'डैशबोर्ड',
    chat: 'चैट',
    symptomChecker: 'लक्षण जांच',
    symptoms: 'लक्षण',
    history: 'स्वास्थ्य इतिहास',
    reports: 'रिपोर्ट्स',
    profile: 'प्रोफाइल',
    healthTips: 'हेल्थ टिप्स',
    hospitals: 'अस्पताल',
    admin: 'एडमिन',
    login: 'लॉगिन',
    logout: 'लॉगआउट',
    signIn: 'साइन इन',
    signOut: 'साइन आउट',
    settings: 'सेटिंग्स',
    adminPanel: 'एडमिन पैनल',
    languageToggle: 'EN / HI',

    // ─── Landing page ──────────────────────────────────────────────────────
    landingTagline: 'एआई स्वास्थ्य जागरूकता प्लेटफॉर्म',
    landingTitle: 'लक्षण समझें और आत्मविश्वास के साथ अगला कदम उठाएं।',
    landingSubtitle: 'हेल्थबॉट एआई चैट, गाइडेड लक्षण जांच, रिपोर्ट्स और अस्पताल खोज को रोज़मर्रा के स्वास्थ्य निर्णयों के लिए एक सुरक्षित कार्यक्षेत्र में लाता है।',
    getStarted: 'शुरू करें',
    signInToChat: 'चैट के लिए साइन इन करें',
    aiGuidance247: '24/7',
    aiGuidanceLabel: 'एआई गाइडेंस',
    riskStatLabel: 'जोखिम',
    riskAwareLabel: 'सचेत ट्रायज',
    secureLabel: 'सुरक्षित',
    historyLabel: 'इतिहास',
    platformFeaturesEyebrow: 'प्लेटफॉर्म फीचर्स',
    platformFeaturesTitle: 'पहले लक्षण के बाद उपयोगकर्ताओं को जो चाहिए वह सब',
    platformFeaturesDesc: 'उन्नत कार्ड, चिकित्सीय स्पष्टता, और प्रमाणित वर्कस्पेस जैसा डार्क-मोड अनुभव।',
    howItWorksEyebrow: 'यह कैसे काम करता है',
    howItWorksTitle: 'लक्षण से कार्रवाई तक एक गाइडेड प्रवाह',
    howItWorksDesc: 'सरल चरण अनुभव को केंद्रित रखते हैं, साथ ही रिपोर्ट, इतिहास और देखभाल खोज के लिए संदर्भ भी बनाए रखते हैं।',
    readyWhenYouAre: 'जब आप तैयार हों',
    startHealthTrail: 'आज एक बेहतर स्वास्थ्य असेसमेंट ट्रेल शुरू करें।',
    createAccountDesc: 'चैट, लक्षण जांच, रिपोर्ट और अस्पताल सुझावों को एक सुरक्षित कार्यक्षेत्र में जोड़ने के लिए अकाउंट बनाएं।',
    createAccount: 'अकाउंट बनाएं',
    liveAssessment: 'लाइव असेसमेंट',
    careGuidance: 'देखभाल मार्गदर्शन',
    symptomContextLabel: 'लक्षण संदर्भ',
    riskReviewLabel: 'जोखिम समीक्षा',
    recommendedActionLabel: 'सुझावित कार्रवाई',
    exploreWorkflow: 'वर्कफ्लो देखें',
    stepLabel: 'चरण',
    triage: 'ट्रायज',

    // Landing feature cards
    feature_aiChat_title: 'एआई हेल्थ चैट',
    feature_aiChat_desc: 'अगले कदम, सुरक्षा जांच और स्पष्ट देखभाल सुझावों के साथ संरचित स्वास्थ्य मार्गदर्शन।',
    feature_symptomChecker_title: 'लक्षण जांच',
    feature_symptomChecker_desc: 'अवधि, गंभीरता, संबंधित लक्षण और जोखिम स्तर को कैप्चर करने वाली गाइडेड ट्रायज।',
    feature_hospitalDiscovery_title: 'अस्पताल खोज',
    feature_hospitalDiscovery_desc: 'जब लक्षणों को चिकित्सा ध्यान की आवश्यकता हो तो विशेषज्ञता के अनुसार नजदीकी देखभाल विकल्प खोजें।',
    feature_healthReports_title: 'हेल्थ रिपोर्ट्स',
    feature_healthReports_desc: 'दृश्य सारांश जो बातचीत और लक्षण जांच को उपयोगी ट्रेंड्स में बदलते हैं।',
    feature_medicalHistory_title: 'चिकित्सा इतिहास',
    feature_medicalHistory_desc: 'चैट खोजे बिना पिछली स्वास्थ्य गतिविधि की व्यवस्थित समयरेखा रखें।',
    feature_healthInsights_title: 'हेल्थ इनसाइट्स',
    feature_healthInsights_desc: 'दैनिक टिप्स और अलर्ट जो उपयोगकर्ताओं को देखभाल निर्णयों के बीच सूचित रखते हैं।',

    // Landing how-it-works steps
    step1_title: 'लक्षण साझा करें',
    step1_desc: 'चैट या गाइडेड चेकर से शुरू करें और जरूरी विवरण जोड़ें।',
    step2_title: 'जोखिम देखें',
    step2_desc: 'हेल्थबॉट गंभीरता, संभावित अगले कदम और तात्कालिकता संकेत का सारांश देता है।',
    step3_title: 'संदर्भ के साथ कार्य करें',
    step3_desc: 'असेसमेंट सेव करें, रिपोर्ट मॉनिटर करें, या जरूरत पड़ने पर अस्पताल खोजें।',

    // ─── Dashboard ─────────────────────────────────────────────────────────
    goodMorning: 'सुप्रभात',
    goodAfternoon: 'नमस्ते',
    goodEvening: 'शुभ संध्या',
    welcomeBack: 'वापसी पर स्वागत है। आज अपना स्वास्थ्य जांचें — एक त्वरित चैट में 30 सेकंड लगते हैं।',
    recentHighRisk: 'आपको एक उच्च-जोखिम घटना थी',
    howAreYouFeeling: 'अब आप कैसा महसूस कर रहे हैं?',
    openChat: 'चैट खोलें',
    healthScore: 'स्वास्थ्य स्कोर',
    activeStreak: 'सक्रिय स्ट्रीक',
    daysEngaged: 'दिन सक्रिय',
    healthRecords: 'स्वास्थ्य रिकॉर्ड',
    totalEntries: 'कुल प्रविष्टियां',
    notifications: 'सूचनाएं',
    newUpdates: 'नई अपडेट',
    quickActions: 'त्वरित क्रियाएं',
    recentActivity: 'हाल की गतिविधि',
    todaysTips: 'आज के टिप्स',
    viewAll: 'सब देखें',
    allTips: 'सभी टिप्स',
    noActivityYet: 'अभी कोई गतिविधि नहीं — चैट या लक्षण जांच से शुरू करें।',
    noTipsAvailable: 'अभी कोई टिप्स उपलब्ध नहीं है।',
    aiChat: 'एआई चैट',
    wellness: 'वेलनेस',

    // ─── Chat page ─────────────────────────────────────────────────────────
    chatbotTitle: 'हेल्थ चैटबॉट',
    chatbotSubtext: 'जब चाहें नई हेल्थ असेसमेंट शुरू करें ताकि रिकॉर्ड साफ रहे।',
    newAssessment: 'नई हेल्थ असेसमेंट शुरू करें',
    askPlaceholder: 'स्वास्थ्य प्रश्न पूछें… (भेजने के लिए Enter, नई लाइन के लिए Shift+Enter)',
    askAi: 'एआई से पूछें',
    generating: 'उत्तर बनाया जा रहा है...',
    startConversation: 'बातचीत शुरू करें',
    startConversationDesc: 'एक स्वास्थ्य प्रश्न पूछें और मैं सत्यापित चिकित्सा स्रोतों के आधार पर जानकारी दूंगा।',
    healthChatbotHeader: 'हेल्थ चैटबॉट',
    aiHealthAwareness: 'एआई-संचालित स्वास्थ्य जागरूकता — चिकित्सा सलाह का विकल्प नहीं',
    chatDisclaimer: 'हेल्थबॉट गलतियाँ कर सकता है। किसी योग्य पेशेवर से महत्वपूर्ण स्वास्थ्य जानकारी सत्यापित करें।',
    dismiss: 'खारिज करें',
    couldNotLoadConversation: 'बातचीत लोड नहीं हो सकी',
    couldNotStartConversation: 'बातचीत शुरू नहीं हो सकी',

    // Chat structured response
    summary: 'हेल्थ असेसमेंट सारांश',
    symptomsDetected: 'पहचाने गए लक्षण',
    riskLevel: 'जोखिम स्तर',
    recommendedAction: 'सुझावित कार्रवाई',
    highAction: 'तुरंत चिकित्सा सहायता लें और नीचे दिए गए अस्पताल सुझाव देखें।',
    mediumAction: 'लक्षणों पर नजर रखें और जारी रहने पर डॉक्टर से परामर्श लें।',
    lowAction: 'अभी आराम, पानी और निगरानी की सलाह दी जाती है।',
    nextSteps: 'अगले कदम',
    nextStepsBody: '2 से 3 दिन तक लक्षण देखें, या चेतावनी संकेत हों तो तुरंत कार्रवाई करें।',
    chatHistory: 'चैट इतिहास',
    noChats: 'अभी कोई चैट नहीं है।',
    possibleCauses: 'संभावित कारण',
    prevention: 'बचाव',
    consultDoctor: 'डॉक्टर से कब मिलें',
    recommendedHospitals: 'सुझावित अस्पताल',
    liveUpdate: 'नया असेसमेंट रियल टाइम में सिंक हुआ है।',
    confidence: 'विश्वास स्तर',
    promptVersion: 'प्रॉम्प्ट वर्जन',

    // ─── Symptom Checker ───────────────────────────────────────────────────
    guidedTriage: 'गाइडेड ट्रायज',
    stepPrimarySymptoms: 'मुख्य लक्षण',
    stepDurationSeverity: 'अवधि और गंभीरता',
    stepAssociatedSymptoms: 'संबंधित लक्षण',
    stepHealthProfile: 'स्वास्थ्य प्रोफाइल',
    stepResult: 'परिणाम',
    selectPrimarySymptoms: 'अपने मुख्य लक्षण चुनें',
    searchSymptoms: 'लक्षण खोजें',
    duration: 'अवधि',
    severity: 'गंभीरता',
    mildLabel: '1 = हल्का',
    moderateLabel: '5 = मध्यम',
    severeLabel: '10 = गंभीर',
    associatedSymptoms: 'संबंधित लक्षण',
    noneOfThese: 'इनमें से कोई नहीं',
    healthProfileSnapshot: 'स्वास्थ्य प्रोफाइल स्नैपशॉट',
    age: 'आयु',
    gender: 'लिंग',
    genderNotSpecified: 'अनिर्दिष्ट',
    genderMale: 'पुरुष',
    genderFemale: 'महिला',
    genderOther: 'अन्य',
    genderPreferNot: 'बताना नहीं चाहते',
    city: 'शहर',
    cityPlaceholderShort: 'जैसे फगवाड़ा',
    medicalNotes: 'चिकित्सा टिप्पणियाँ',
    analysingSymptoms: 'आपके लक्षणों का विश्लेषण हो रहा है...',
    emergencyWarningTitle: 'आपातकालीन चेतावनी संकेत मिले',
    emergencyWarningDesc: 'कृपया तुरंत आपातकालीन चिकित्सा देखभाल लें।',
    assessmentResult: 'जांच परिणाम',
    recommendedActions: 'सुझावित कार्रवाई',
    suggestedSpecialists: 'सुझावित विशेषज्ञ',
    nearestHospitals: 'नजदीकी अस्पताल',
    noNearbyHospitals: 'आपके शहर के लिए नजदीकी अस्पताल सुझाव नहीं मिले।',
    back: 'वापस',
    next: 'आगे',
    getAssessment: 'जांच करें',
    startOver: 'फिर से शुरू करें',
    saveToHistory: 'इतिहास में सेव करें',
    continueInChat: 'चैट में जारी रखें',
    other: 'अन्य',
    describeOtherSymptom: 'अन्य लक्षण बताएं',
    noSymptomsMatch: 'आपकी खोज से कोई लक्षण नहीं मिला।',
    savedToHistory: 'आपके स्वास्थ्य इतिहास में सेव हो गया।',
    analysisFailedRetry: 'विश्लेषण विफल हुआ। कृपया फिर से कोशिश करें।',
    couldNotOpenChat: 'चैट नहीं खुल सका। कृपया मैन्युअल रूप से चैट पर जाएं।',

    // ─── Hospitals page ────────────────────────────────────────────────────
    findHospitals: 'अस्पताल खोजें',
    searchByCityOrLocation: 'शहर से खोजें या नजदीकी देखभाल के लिए अपना स्थान उपयोग करें।',
    useMyLocation: 'मेरा स्थान उपयोग करें',
    shareLocation: 'स्थान साझा करें',
    shareLocationDesc: 'दूरी के आधार पर अस्पताल देखने और रेडियस फ़िल्टरिंग सक्षम करने के लिए अपना स्थान साझा करें।',
    allSpecialties: 'सभी विशेषज्ञताएं',
    emergencyOnly: 'केवल आपातकाल',
    anyDistance: 'कोई भी दूरी',
    kmAway: 'किमी दूर',
    minDrive: 'मिनट की दूरी',
    emergency24h: '24 घंटे आपातकाल',
    searchHospitalsTitle: 'अस्पताल खोजें',
    enterCityOrLocation: 'शुरू करने के लिए शहर डालें या स्थान साझा करें।',
    noHospitalsFound: 'कोई अस्पताल नहीं मिला',
    tryDifferentSearch: 'अलग शहर, विशेषज्ञता, या दूरी आज़माएं।',
    noHospitalsWithinRadius: 'के अंदर कोई अस्पताल नहीं मिला',
    tryIncreasingRadius: 'सर्च रेडियस बढ़ाएं या अलग विशेषज्ञता चुनें।',
    quickSearch: 'त्वरित शहर खोज',
    showingForSymptoms: 'हाल की लक्षण जांच के आधार पर अस्पताल दिखाए जा रहे हैं।',
    call: 'कॉल करें',
    directions: 'दिशा-निर्देश',
    hospitalsFoundSingular: 'अस्पताल मिला',
    hospitalsFoundPlural: 'अस्पताल मिले',
    locationDetected: 'स्थान पता चला',
    clearLocation: 'स्थान हटाएं',
    locationDenied: 'स्थान की अनुमति नहीं मिली। कृपया ब्राउज़र सेटिंग में अनुमति दें, फिर फिर से कोशिश करें।',
    locationTimeout: 'स्थान अनुरोध समय से बाहर हो गया। फिर से कोशिश करें।',
    locationUnavailable: 'स्थान पता नहीं चल सका। कृपया शहर से खोजें।',
    geoNotSupported: 'इस ब्राउज़र में जियोलोकेशन समर्थित नहीं है',
    retryLocation: 'फिर कोशिश करें',
    cityPlaceholder: 'शहर, जैसे फगवाड़ा, लुधियाना, दिल्ली',
    detectingLocation: 'स्थान पता किया जा रहा है...',
    locationPermissionDenied: 'स्थान की अनुमति नहीं मिली',
    locationTimedOut: 'स्थान अनुरोध समय से बाहर',
    couldNotDetectLocation: 'स्थान पता नहीं चल सका',
    couldNotLoadHospitals: 'अस्पताल लोड नहीं हो सके',

    // ─── Health Reports ────────────────────────────────────────────────────
    healthReportsTitle: 'हेल्थ रिपोर्ट्स',
    overviewTab: 'अवलोकन',
    symptomsTab: 'लक्षण',
    trendsTab: 'ट्रेंड्स',
    aiInsightsTab: 'एआई इनसाइट्स',
    downloadPdf: 'पीडीएफ डाउनलोड करें',
    refreshData: 'रिफ्रेश करें',
    totalChecks: 'कुल जांच',
    highRiskEvents: 'उच्च जोखिम घटनाएं',
    avgRiskScore: 'औसत जोखिम स्कोर',
    reportPeriod: 'रिपोर्ट अवधि',
    noReportData: 'अभी कोई रिपोर्ट डेटा नहीं है।',
    startCheckForReport: 'पहली रिपोर्ट बनाने के लिए लक्षण जांच या चैट पूरा करें।',
    couldNotLoadInsights: 'एआई इनसाइट्स लोड नहीं हो सकीं।',
    regenerateInsights: 'इनसाइट्स फिर बनाएं',
    aiInsightsTitle: 'एआई हेल्थ इनसाइट्स',
    noInsightsYet: 'अभी कोई इनसाइट्स नहीं।',
    completeChecksForInsights: 'व्यक्तिगत इनसाइट्स के लिए कुछ लक्षण जांच पूरी करें।',

    // ─── Health History ────────────────────────────────────────────────────
    healthHistoryTitle: 'स्वास्थ्य इतिहास',
    healthHistoryDesc: 'आपकी पिछली लक्षण जांच और एआई बातचीत।',
    noHistoryYet: 'अभी कोई स्वास्थ्य इतिहास नहीं।',
    startChatOrCheck: 'स्वास्थ्य रिकॉर्ड बनाने के लिए चैट या लक्षण जांच शुरू करें।',

    // ─── Health Tips ───────────────────────────────────────────────────────
    healthTipsTitle: 'हेल्थ टिप्स',
    healthTipsDesc: 'दैनिक वेलनेस सलाह और निवारक देखभाल मार्गदर्शन।',

    // ─── Profile ───────────────────────────────────────────────────────────
    profileTitle: 'प्रोफाइल और सेटिंग्स',
    editProfile: 'प्रोफाइल संपादित करें',
    saveChanges: 'बदलाव सेव करें',

    // ─── Common / shared ───────────────────────────────────────────────────
    loading: 'लोड हो रहा है...',
    error: 'त्रुटि',
    retry: 'फिर से कोशिश करें',
    save: 'सेव करें',
    cancel: 'रद्द करें',
    close: 'बंद करें',
    youAreHere: 'आप यहाँ हैं',
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    () => localStorage.getItem('language') || 'en',
  );

  const changeLanguage = (nextLanguage) => {
    localStorage.setItem('language', nextLanguage);
    setLanguage(nextLanguage);
  };

  const value = useMemo(
    () => ({
      language,
      setLanguage: changeLanguage,
      t: dictionary[language] || dictionary.en,
    }),
    [language],
  );

  return (
    <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
  );
}
